app/meals/routes.py
import os
import re

from flask import (
    Blueprint,
    url_for,
    redirect,
    render_template, request, flash
)

from flask_paginate import Pagination, get_page_parameter
from flask_login import login_required
from flask_mail import Mail, Message
from flask_login import current_user

from .models import Meal, Ingredient, Category, Area, MealIngredient
from .. import db
from ..users.models import UserFavorite, UserFavoriteCategory, User
from ..users.forms import CommentForm
from ..users.models import UserComments, UserActivities
from ..index.routes import top_fives


static_path = os.path.abspath(
                                os.path.join(
                                    os.path.dirname(
                                        os.path.abspath(__file__)), 'static'))

meals_bp = Blueprint(
    'meals',
    __name__,
    template_folder='templates',
    url_prefix='/meal',
    static_folder='static',
    static_url_path=static_path
)


def get_fav_catgories(category_id):
    check = db.session.query(UserFavoriteCategory).filter(
        UserFavoriteCategory.category_id.like(category_id),
        UserFavoriteCategory.user_id.like(current_user.id)).first()
    return check


@meals_bp.route('/')
def test_route():
    if not current_user.is_authenticated:
        return redirect('/')
    page = request.args.get('page', 1, type=int)
    meallist = Meal.query.paginate(page, 6, False)
    next_url = url_for('meals.test_route', page=meallist.next_num) \
        if meallist.has_next else None
    prev_url = url_for('meals.test_route', page=meallist.prev_num) \
        if meallist.has_prev else None

    return render_template(

        'main_page.html',
        meallist=meallist,
        next_url=next_url,
        prev_url=prev_url,

    )


@meals_bp.route('/categories')
def categories_list():
    categories = Category.query.all()
    checker = None

    if current_user.is_authenticated:
        checker = db.session.query(Category).\
            join(UserFavoriteCategory).\
            filter_by(user_id=current_user.id).all()

    return render_template(
        'category_list.html',
        categories=categories,
        checker=checker)


@meals_bp.route('/areas')
def areas_list():
    areas = Area.query.all()
    return render_template(
        'areas_list.html',
        areas=areas)


@meals_bp.route('/search/')
def meal_search():
    meal_name = request.args.get('meal_name')
    page = request.args.get('page', 1, type=int)
    meallist = db.session.query(Meal).filter(
        Meal.name.contains(meal_name.lower()))\
        .paginate(page, 6, False)
    if meallist:
        next_url = url_for('meals.test_route', page=meallist.next_num) \
            if meallist.has_next else None
        prev_url = url_for('meals.test_route', page=meallist.prev_num) \
            if meallist.has_prev else None

        return render_template(
            'main_page.html',
            meallist=meallist,
            next_url=next_url,
            prev_url=prev_url,)
    else:
        return redirect('/meal')


@meals_bp.route('/search_by_username/')
@login_required
def meal_search_by_username():
    u_name = request.args.get('srch_user_username')
    page = request.args.get('page', 1, type=int)
    meallist = None
    if isinstance(u_name, str) and not u_name.isdecimal():
        meallist = db.session.query(Meal)\
            .join(User).filter(User.username.contains(u_name.lower()))\
            .paginate(page, 6, False)
    elif u_name.isdecimal():
        meallist = db.session.query(Meal)\
            .join(User).filter(User.id.like(int(u_name)))\
            .paginate(page, 6, False)
    if meallist:
        next_url = url_for('meals.test_route', page=meallist.next_num) \
            if meallist.has_next else None
        prev_url = url_for('meals.test_route', page=meallist.prev_num) \
            if meallist.has_prev else None
        return render_template(
            'main_page.html',
            meallist=meallist,
            next_url=next_url,
            prev_url=prev_url)
    else:
        return redirect('/meal')


@meals_bp.route('/areas/<int:a_id>/')
@login_required
def meals_by_countries(a_id: int):
    page = request.args.get('page', 1, type=int)

    meallist = Meal.query.filter_by(area_id=a_id).paginate(page, 6, False)
    next_url = url_for(
        'meals.meals_by_countries',
        a_id=a_id,
        page=meallist.next_num)\
        if meallist.has_next else None
    prev_url = url_for(
        'meals.meals_by_countries',
        a_id=a_id,
        page=meallist.prev_num)\
        if meallist.has_prev else None

    return render_template(
        'main_page.html',
        meallist=meallist,
        next_url=next_url,
        prev_url=prev_url,

    )


@meals_bp.route('/category/<int:c_id>/')
@login_required
def meals_by_category(c_id):
    page = request.args.get('page', 1, type=int)

    meallist = Meal.query.filter_by(category_id=c_id).paginate(page, 6, False)
    next_url = url_for(
        'meals.meals_by_category',
        c_id=c_id,
        page=meallist.next_num)\
        if meallist.has_next else None
    prev_url = url_for(
        'meals.meals_by_category',
        c_id=c_id,
        page=meallist.prev_num)\
        if meallist.has_prev else None

    return render_template(
        'main_page.html',
        meallist=meallist,
        next_url=next_url,
        prev_url=prev_url,

    )


@meals_bp.route('/add-favorite/<int:meal_id>', methods=['GET'])
@login_required
def add_favorite(meal_id):
    bb = db.session.query(UserFavorite).filter(
        UserFavorite.meal_id.like(meal_id),
        UserFavorite.user_id.like(current_user.id)).first()

    # User Activity
    user_activity = UserActivities.query.filter_by(
        user_id=current_user.id).first()

    if not bb:
        check = False
        user_favorite = UserFavorite(
            user_id=current_user.id,
            meal_id=meal_id
        )

        db.session.add(user_favorite)

        # User Activity +
        user_activity.favorite_meals += 1
    else:
        check = True
        db.session.delete(bb)

        # User Activity -
        user_activity.favorite_meals -= 1

    db.session.commit()
    print(request.referrer)

    if 'meal/meal_info' in request.referrer:
        return redirect(url_for('meals.meal_info', m_id=meal_id, check=check))
    else:
        return redirect(url_for('users.users_profiles', u_id=current_user.id))


@meals_bp.route('/meal_info/<int:m_id>/', methods=['GET'])
def meal_info(m_id):
        meal = Meal.query.filter_by(id=m_id).first()
        ingredients = MealIngredient.query.filter_by(meal_id=m_id).all()
        form = CommentForm()
        try:
            check = db.session.query(UserFavorite).filter(
                UserFavorite.meal_id.like(m_id),
                UserFavorite.user_id.like(current_user.id)
            ).first()
        except:
            check = False
        page = request.args.get('page', 1, type=int)
        comments = UserComments.query.\
            filter(UserComments.meal_id == m_id).\
            order_by(UserComments.date_posted.desc()).\
            paginate(per_page=2, page=page)
        fav_count = len(db.session.query(UserFavorite).filter(
            UserFavorite.meal_id.like(m_id)).all())
        if not current_user.is_authenticated:
            if m_id in [x.id for x in top_fives()]:
                meal = Meal.query.filter_by(id=m_id).first()
            else:
                return redirect(url_for('users.login'))
        else:
            meal = Meal.query.filter_by(id=m_id).first()
        return render_template('meal_info.html',
                               meal=meal, ingredients=ingredients, check=check,
                               form=form, comments=comments, page=page,
                               m_id=m_id, fav_count=fav_count)


@meals_bp.route('/meal_info/<int:m_id>/', methods=['POST'])
@login_required
def meal_info_post(m_id):
    form = CommentForm()
    if form.is_submitted():
        comment = UserComments(
            content=form.content.data,
            user_id=current_user.id,
            meal_id=m_id)
        db.session.add(comment)

        # User Activity
        user_activity = UserActivities.query.filter_by(
            user_id=current_user.id).first()
        user_activity.comments += 1

        db.session.commit()
        return redirect(url_for('meals.meal_info',
                                m_id=m_id))


@meals_bp.route('/add-favorite-category/<int:category_id>', methods=['GET'])
@login_required
def add_favorite_category(category_id):
    bb = db.session.query(UserFavoriteCategory).filter(
        UserFavoriteCategory.category_id.like(category_id),
        UserFavoriteCategory.user_id.like(current_user.id)).first()

    # User Activity
    user_activity = UserActivities.query.filter_by(
        user_id=current_user.id).first()

    if not bb:
        user_favorite_category = UserFavoriteCategory(
            user_id=current_user.id,
            category_id=category_id
        )

        db.session.add(user_favorite_category)

        # User Activity +
        user_activity.favorite_categories += 1
    else:
        db.session.delete(bb)

        # User Activity -
        user_activity.favorite_categories -= 1

    db.session.commit()

    if 'meal/categories' in request.referrer:
        return redirect(url_for('meals.categories_list'))
    else:
        return redirect(url_for('users.users_profiles', u_id=current_user.id))


@meals_bp.route('/search/<meal_name>/')
@login_required
def meal_search_name(meal_name):
    meal = Meal.query.filter(Meal.name.contains(str(meal_name).lower())).\

app/meals/templates/areas_list.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
{% for country in areas  %}
 <div class="col-sm-3">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{country.name}}</h5>
        <a href={{url_for('meals.meals_by_countries' ,  a_id = country.id)}}  class="btn btn-primary">Recipes from this country</a>
      </div>
    </div>
  </div>
{% endfor %}
</div>


{% endblock content %}

app/meals/templates/category_list.html
{% extends 'base.html' %}


   
{% block title %}
   All Categories 
{% endblock title %}



{% block content %}
    <link rel="stylesheet" href={{ url_for('meals.static', filename='css/categories.css') }}  />
        <div class="product-container">
            <div class="container">
                <div class="row">

                        {% for category in categories  %}
                        
                            <div class="col-sm-4">
                        <div class="product-card">

                            <div class="card-thumbnail">
                                <img class="img-responsive" src={{category.img_link}}>
                            </div>

                            <div class="card-content">
                                <div class="send">
  
                                    <i class="fa fa-cutlery" aria-hidden="true"></i>
                                </div>
                                <h1 class="card-title">
								{{category.name}}
									</h1>
							<span>
                            {% if current_user.is_authenticated %}
                              {% if category in checker %}
                                    <a href="{{ url_for('meals.add_favorite_category', category_id = category.id) }}">Remove from favorite categories&#11088</a>
                                {% else %}
                                     <a href="{{ url_for('meals.add_favorite_category', category_id = category.id) }}"> Add to favorite categories &#128976</a>
                                {% endif %}  
                            {% endif %}
 							</span>
                                <h2 class="card-sub-title">
								 Yummy Meals
							</h2>
                                <p class="description">
                                   {{category.description}}
                                </p>
                                <p style="margin-top:20px;"><a href={{url_for('meals.meals_by_category' , c_id=category.id) }} >Recipes from this category</a></p>
                              
                                </ul>   
                            </div>
                        </div>
                    </div>
                        
                        {% endfor %}
                  
                    </div>
                </div>
            </div>
        </div>
{% endblock content %}
    

app/meals/templates/main_page.html
{% extends 'base.html' %}


   
{% block title %}
Meal main page
{% endblock title %}



{% block content %}
    <link rel="stylesheet" href={{ url_for('meals.static', filename='css/main.css') }}  />

<div class="flexbox">
  {% if meallist.items|length == 0  %}
    <p>Nothing Found !</p>
  {% endif %}
    {% for meal in meallist.items %}
        <div class="food-card" style="background-image:url(
          {% if meal.author_id != 1 %}
            {{url_for('meals.static' ,filename = meal.img_link )}}
          {% else %}
            {{meal.img_link}}
          {% endif %}
          );">
    <div class="food-card-content">
      <div class="heading show">
        <h2><a href="/meal/meal_info/{{meal.id}}">{{meal.name}}</a></h2>
      <div class="shadow"></div>
      </div>
      <div class="heading author show">
        <h5>By <a href="{{url_for('users.users_profiles' , u_id = meal.user.id)}}" class="profile">{{meal.user.username}}</a></h5>
      <div class="shadow"></div>
      </div>
      <div class="hover-content">
      <div class="food-card-properties">
        <div><i class="fa fa-globe" aria-hidden="true"></i><p>{{meal.area.name}}</p></div>
        <div><i class="fa fa-tag" aria-hidden="true"></i><p>{% if meal.tags == None %} - {% else %} {{meal.tags}} {% endif %}</p></div>
        <div><i class="fa fa-cutlery" aria-hidden="true"></i><p>{{meal.category.name}}</p></div>
      </div>  
        <hr>
        <div class="content">{{meal.instructions}}<div class="show-less"></div></div>
        <a href={{url_for('meals.meal_info' ,m_id=meal.id) }} class="view-more">View More-></a>
      </div>
    </div>
  </div>


    {% endfor %}
</div> 

<div class="nav_btns">
{% if prev_url %}
    <a href="{{ prev_url }}"> Previous |  </a>
    {% endif %}
    {% if next_url %}  
    <a href="{{ next_url }}">  | Next </a>
    {% endif %}
</div>
   

{% endblock content %}
    