app/index/routes.py
import os
import random
from operator import itemgetter
import json

from flask import (
    Flask,
    g,
    url_for,
    redirect,
    render_template,
    Blueprint,
    session
)
from flask_login import current_user, login_required
from flask_socketio import SocketIO
from sqlalchemy import func, desc, and_, select

from .. import db
from ..meals.models import Meal
from ..users.models import UserComments, UserFavorite, User
from ..chat import events


static_path = os.path.abspath(os.path.join(os.path.dirname(
    os.path.abspath(__file__)), 'static'))

index_bp = Blueprint(
    'index',
    __name__,
    template_folder='templates',
    url_prefix='/',
    static_folder='static',
    static_url_path=static_path
)


def top_fives():
    mydict = {}
    for record in UserFavorite.query.all():
        mydict[record.meal_id] = len(UserFavorite.query.
                                     filter_by(meal_id=record.meal_id).all())
    res = dict(sorted(mydict.items(), key=itemgetter(1), reverse=True)[:5])
    tops = Meal.query.filter(Meal.id.in_(list(res.keys()))).all()
    tops = sorted(tops, key=lambda o: list(res.keys()).index(o.id))
    return tops


@index_bp.route('/')
def index():
    tops = top_fives()

    #chat
    name = 'Guest'
    if current_user.is_authenticated:
        name = current_user.username
    room = 'main_room'

    session['name'] = name
    session['room'] = room
    name = session.get('name', '')
    room = session.get('room', '')

    return render_template(
        'index_page.html',
        tops=tops,
        name=name,
        room=room)


@index_bp.route('/presentation')
def presentation():
    return redirect('https://view.genial.ly/5f2f99770c24590d87b624b9/presentation-yummy-meals')

app/index/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href= "{{ url_for('index.static', filename='css/base.css') }}"  />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="shortcut icon" href={{ url_for('index.static', filename='media/logo1.png') }}>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"  crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for('index.static',filename='css/responsive.css') }}">
       
      
    <title>  
    {% block title %}

    {% endblock title %}
    </title>  
    
    {% block links %}

    {% endblock links %}

</head>
<body id="page-top">
    
    {% include 'header.html' %}
<section id="preloader-section">
<div id="preloader">
                <div id="ctn-preloader" class="ctn-preloader">
                    <div class="animation-preloader">
                        
                        <!-- Spinner -->
                        <div class="spinner"></div>
                        
                        <!-- Start: Text Loading -->
                        <div class="txt-loading">
                            <span data-text-preloader="Y" class="letters-loading">M</span>
                            <span data-text-preloader="U" class="letters-loading">E</span>
                             <span data-text-preloader="M" class="letters-loading">A</span>
                            <span data-text-preloader="M" class="letters-loading">L</span>
                             <span data-text-preloader="Y" class="letters-loading">S</span> 
                            <span data-text-preloader="" class="letters-loading">&nbsp</span>
                            <span data-text-preloader="W" class="letters-loading">L</span>
                            <span data-text-preloader="A" class="letters-loading">O</span>
                            <span data-text-preloader="I" class="letters-loading">A</span>
                            <span data-text-preloader="T" class="letters-loading">D</span>
                       
                        </div>
                        <!-- End: Text Loading -->

                    </div>

                    <!-- Start: Preloader sides - Model 1 -->
                    <div class="loader-section section-left"></div>
                    <div class="loader-section section-right"></div>
                    <!-- End: Preloader sides - Model 1 -->

                </div>
            </div>
        <section/>
    <main class="main-content">

    {% block content %}

    {% endblock content %}

    </main>
    

    <script src = 'https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

    <script src = 'https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js'></script>
    <script src = 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js'></script>
   
    <script src = {{url_for('index.static', filename='js/script.js') }} ></script>

    {% block scripts %}

    {% endblock scripts %}
    {% extends 'footer.html' %}

</body>
</html>

app/index/templates/footer.html



  <!-- Site footer -->
    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <h6>About</h6>
            <p class="text-justify">Here's our ACA second course final Flask project. <br/>
            Authors: Vlad Harutyunyan, Hayk Sahakyan, <br/> Zhora Karyan and Ruzanna Ordyan<br>
              <a href="{{ url_for('index.presentation') }}">&#10024; Website presentation</a></p>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Categories</h6>
            <ul class="footer-links">
                <li><a href="{{ url_for('meals.categories_list') }}">All Categories</a></li>
            </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Quick Links</h6>
            <ul class="footer-links">
             {% if  current_user.username %}
                <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
                <li><a href="{{ url_for('users.account_get') }}">Settings</a></li>
                <li><a href="{{ url_for('users.users_profiles' , u_id = current_user.id) }}">My profile</a></li>
                <li><a href="{{ url_for('users.new_recipe_get') }}">New Recipe</a></li>
                <li><a href="{{ url_for('users.support_get') }}">Support</a></li>
                <li><a href="{{ url_for('users.messages_get') }}">Private Messages (PM) </a></li>
                {% else %} 
                <li><a href="{{ url_for('users.login') }}">Login</a></li>
                <li><a href="{{ url_for('users.register') }}">Register</a></li>
            {% endif %}
            </ul>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyright &copy; 2020 All Rights Reserved
            </p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="dribbble" href="https://github.com/Vlad-Harutyunyan/YummyMeals"><i class="fa fa-github"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
</footer>

app/index/templates/header.html


<link rel="stylesheet" href="{{url_for('index.static',filename='css/header.css') }}">

<header style="display:flex">   
 
  <h1><a style="display:flex;" href="/"><img width="321" height="70", src="{{url_for('index.static' ,  filename='media/Logo2-1.png') }}" ></a></h1>

  
<div class="search-form resp_big_search">
<p class="head_search_txt">Search</p>
 <form  method = 'GET' action="{{url_for('meals.meal_search')}}">
    <input  class = "head_search_sbmit"type = 'submit' value="search"></input>
    <input class="head_search_inp" type='text' name="meal_name"></input>   
    <button style = "outline:none;" class="head_search_btn" type = 'submit'></button>
  </form>
</div> 
 
  <div id="nav-trigger" role="button">
    <div class="line l-01"></div>
    <div class="line l-02"></div>
    <div class="line l-03"></div>
    <div class="line l-04"></div>
  </div>

  
</header>

<!-- main-content -->



<nav id="side-nav">
  <ul class="nav_navigation">
    <li class="item-has-children">
      <a href="#0">User</a>
      <ul class="sub-menu">
    {% if  current_user.is_authenticated %}
      <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
      <li><a href="{{ url_for('users.account_get') }}">Settings</a></li>
      <li><a href="{{ url_for('users.users_profiles' , u_id = current_user.id) }}">My profile</a></li>
      <li><a href="{{ url_for('users.new_recipe_get') }}">New Recipe</a></li>
      <li><a href="{{ url_for('users.user_friend_requests') }}">Friend Requests</a></li>
      <li><a href="{{ url_for('users.messages_get') }}" target="popup" onclick="window.open('{{ url_for('users.messages_get') }}','popup','width=600,height=400'); return false;"> Private Messages (PM) </a></li>	  	  
    {% else %}
      <li><a href="{{ url_for('users.login') }}">Login</a></li>
      <li><a href="{{ url_for('users.register') }}">Register</a></li>
    {% endif %}
    
    
      </ul>
    </li> 
    <!-- item-has-children -->

    <li><a href="{{ url_for('meals.categories_list') }}">All Categories</a></li>
    <li><a href="{{ url_for('meals.areas_list') }}">All Areas</a></li>

  </ul> 
  <!-- nav_navigation -->

  <ul class="nav_navigation single-item-wrapper">
    <li><a href="#0"></a></li>
    <li><a href="{{ url_for('users.support_get') }}">Support</a></li>
  </ul>
  <!-- single-item-wrapper -->
  <hr/>
  <form class="form-inline" method = 'GET' action="{{url_for('meals.meal_search_by_username')}}">
    <label for='srch_by_username' class = 'badge badge-primary text-wrap' style="margin:10px 0" >>>> </label>
        <input id="srch_by_username" class="form-control mr-sm-2" type="search" placeholder="Search by username" aria-label="Search" name = "srch_user_username">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
	
	  <form class="form-inline" method = 'GET' action="{{url_for('meals.meal_search_by_ingredient')}}">
    <label for='srch_by_uingredient' class = 'badge badge-primary text-wrap' style="margin:10px 0" >>>></label>
        <input id="srch_by_ingredient" class="form-control mr-sm-2" type="search" placeholder="Search by ingredient" aria-label="Search" name = "srch_ingredient">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <form  method = 'GET' action="{{url_for('meals.meal_search')}}">
      <input  class = "head_search_sbmit"type = 'submit' value="search"></input>
      <label for='srch_by_title_keyword' class = 'badge badge-primary text-wrap' style="margin:10px 0" >>>></label>
        <input id='srch_by_title_keyword' class="form-control mr-sm-2" type='text' name="meal_name" placeholder="Search by title" aria-label="Search"></input>   
        <button  class="btn btn-outline-success my-2 my-sm-0" type = 'submit'>Search</button> 
  </form>
  <div class="nav_navigation socials">
    <a class="fa fa-github" href="https://github.com/Vlad-Harutyunyan/YummyMeals"></a>
    <a class="fa fa-google-plus" href="mailto:yummymealsbook@gmail.com"></a>
  </div>
  <!-- socials -->  
</nav>

app/index/templates/index_page.html
{% extends 'base.html' %}

{% block title %}
Home page
{% endblock title %}

{% block content %}
<link rel="stylesheet" href="{{url_for('index.static',filename='css/index.css') }}">

<div class="main_wrapper">

<div class='chat_sidebar' >


  <script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
  

  <!-- Emoji Data -->
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>


        <script type="text/javascript" charset="utf-8">
          //Emojies
         
        // $('#em_trigger').emojiPicker('destroy');
  
            var socket;
            $(document).ready(function(){
                socket = io.connect('http://' + document.domain + ':' + location.port+'/');
                socket.on('connect', function() {
                    socket.emit('joined', {});
                });
                socket.on('user_leave', function(data) {
                    $('#chat').val($('#chat').val() + '<' + data.msg +'>\n');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight); 
                    let cnt = data.clients_count
                    $('#onlineStatusChecker').html(`Online ${cnt} user`) ;
                }); 
                socket.on('status', function(data) {
                    $('#chat').val($('#chat').val() + '<' + data.msg +'>\n');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight); 
                    let cnt = data.clients_count
                    $('#onlineStatusChecker').html(`Online ${cnt} user`) ;
                });   
                  
                socket.on('message', function(data) { 
                    $('#chat').val($('#chat').val() + data.msg + '\n'); 
                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
                });
                $('#text').keypress(function(e) {
                    var code = e.keyCode || e.which;
                    if (code == 13) {
                        text = $('#text').val();
                        $('#text').val('');
                        socket.emit('text', {msg: text});
                    }
                });
            });
        </script>

        <h1 style="font-size:30px;text-align:center;margin-bottom:10px;">Online chat</h1>
        <p id="onlineStatusChecker"></p>
         <textarea id="chat" cols="20" rows="33" style="width:100%;" disabled></textarea><br><br>
        {% if current_user.is_authenticated %}
          <input id="text" size="80" placeholder="Enter your message here" style="width:100%; height:35px;"><br><br>
        {% else %}  
          <p>Please <a href="{{url_for('users.register')}}">register</a>,or  <a href="{{url_for('users.login')}}">login</a> to leave comment !!</p>
        {% endif %}

</div>


<div class="cont s--inactive" >
  <!-- cont inner start -->
  <h1 style="font-size:30px;text-align:center;margin:20px auto;">Top Recipes</h1>

  <div class="cont__inner">


  {% for rec in range(tops|length)  %}
   <!-- el start -->
    <div class="el" >
      <div class="el__overflow">
        <div class="el__inner">
		{% if tops[rec].img_link != "default.jpg"%}
          <div class="el__bg" style="background:url('{{tops[rec].img_link}}');background-size: cover"></div>
		{% else%}
		   <div class="el__bg" style="background:url({{url_for('meals.static' , filename = "default.jpg")}});background-size: cover"></div> 
		{% endif %}
          <div class="el__preview-cont">
            <h2 class="el__heading">{{tops[rec].name}}</h2>
          </div>
          <div class="el__content">
            <div class="el__text">{{tops[rec].name}}</div>
            <div class="el__text_descr">{{tops[rec].instructions}}</div>
            <div class="el__text_btn" >
            <a class="btn btn-info" href={{url_for('meals.meal_info' , m_id=tops[rec].id)}}> More info </a>
            </div>
            <div class="el__close-btn"></div>
          </div>
        </div>
      </div>
      <div class="el__index" style="margin-bottom: 120px;">
        <div class="el__index-back">{{rec+1}}</div>
        <div class="el__index-front">
          <div class="el__index-overlay" data-index="{{rec+1}}">{{rec+1}}</div>
        </div>
      </div>
    </div>
    <!-- el end -->
  
  {% endfor %}

  </div>
  
  <div class="responsive_top5">
  {% for rec in range(tops|length)  %}
   <!-- el start -->
   <div class="resp_item_main_block">
           <h3>{{tops[rec].name}} -(top {{rec+1}})</h3>
		{% if tops[rec].img_link != "default.jpg"%}
        <img class="top_sect_img" src="{{tops[rec].img_link}}" />
		{% else%}
        <img class="top_sect_img" src="{{url_for('meals.static' , filename = "default.jpg")}}" />
		{% endif %}
          <br/>
          <a class="btn btn-info" href={{url_for('meals.meal_info' , m_id=tops[rec].id)}}> More info </a>
   </div>

  {% endfor %}

  
  </div>
  <!-- cont inner end -->
</div>

</div>


{% endblock content %}